//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mp3scrUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MainWindowPlacement {
            get {
                return ((string)(this["MainWindowPlacement"]));
            }
            set {
                this["MainWindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\gary\\Desktop\\podcasts\\mp3scrUI")]
        public string InitialDirectory {
            get {
                return ((string)(this["InitialDirectory"]));
            }
            set {
                this["InitialDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0001")]
        public string DefaultIndex {
            get {
                return ((string)(this["DefaultIndex"]));
            }
            set {
                this["DefaultIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultEnabled {
            get {
                return ((bool)(this["DefaultEnabled"]));
            }
            set {
                this["DefaultEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://acme.com/feed.htm")]
        public string DefaultUrl {
            get {
                return ((string)(this["DefaultUrl"]));
            }
            set {
                this["DefaultUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("=")]
        public string DefaultUrlPrefix {
            get {
                return ((string)(this["DefaultUrlPrefix"]));
            }
            set {
                this["DefaultUrlPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("acme.xml")]
        public string DefaultDestBase {
            get {
                return ((string)(this["DefaultDestBase"]));
            }
            set {
                this["DefaultDestBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\podcasts\\")]
        public string DefaultDestFolderName {
            get {
                return ((string)(this["DefaultDestFolderName"]));
            }
            set {
                this["DefaultDestFolderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.gocek.org/podcasts/")]
        public string DefaultExistingFeedFolder {
            get {
                return ((string)(this["DefaultExistingFeedFolder"]));
            }
            set {
                this["DefaultExistingFeedFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("acme-")]
        public string DefaultGuidPrefix {
            get {
                return ((string)(this["DefaultGuidPrefix"]));
            }
            set {
                this["DefaultGuidPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultMp3Filter {
            get {
                return ((string)(this["DefaultMp3Filter"]));
            }
            set {
                this["DefaultMp3Filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultIndirectFilter {
            get {
                return ((string)(this["DefaultIndirectFilter"]));
            }
            set {
                this["DefaultIndirectFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultIndirect {
            get {
                return ((bool)(this["DefaultIndirect"]));
            }
            set {
                this["DefaultIndirect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Acme")]
        public string DefaultChannelTitle {
            get {
                return ((string)(this["DefaultChannelTitle"]));
            }
            set {
                this["DefaultChannelTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No RSS feed offered by Acme.")]
        public string DefaultChannelNotes {
            get {
                return ((string)(this["DefaultChannelNotes"]));
            }
            set {
                this["DefaultChannelNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultSortDescending {
            get {
                return ((bool)(this["DefaultSortDescending"]));
            }
            set {
                this["DefaultSortDescending"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultRetainOrphans {
            get {
                return ((bool)(this["DefaultRetainOrphans"]));
            }
            set {
                this["DefaultRetainOrphans"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultStripBaseName {
            get {
                return ((bool)(this["DefaultStripBaseName"]));
            }
            set {
                this["DefaultStripBaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultPrependRelative {
            get {
                return ((string)(this["DefaultPrependRelative"]));
            }
            set {
                this["DefaultPrependRelative"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int DefaultRefreshDays {
            get {
                return ((int)(this["DefaultRefreshDays"]));
            }
            set {
                this["DefaultRefreshDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://ftp.gocek.net/wwwroot/podcasts/")]
        public string DefaultFtpPath {
            get {
                return ((string)(this["DefaultFtpPath"]));
            }
            set {
                this["DefaultFtpPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gocek.net")]
        public string DefaultFtpUserName {
            get {
                return ((string)(this["DefaultFtpUserName"]));
            }
            set {
                this["DefaultFtpUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2010GoWeb-")]
        public string DefaultFtpPassword {
            get {
                return ((string)(this["DefaultFtpPassword"]));
            }
            set {
                this["DefaultFtpPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultPermissionRevoked {
            get {
                return ((string)(this["DefaultPermissionRevoked"]));
            }
            set {
                this["DefaultPermissionRevoked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultAllowHttps {
            get {
                return ((bool)(this["DefaultAllowHttps"]));
            }
            set {
                this["DefaultAllowHttps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultWraparound {
            get {
                return ((bool)(this["DefaultWraparound"]));
            }
            set {
                this["DefaultWraparound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int DefaultMaxWebRequests {
            get {
                return ((int)(this["DefaultMaxWebRequests"]));
            }
            set {
                this["DefaultMaxWebRequests"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultMaintenanceA {
            get {
                return ((string)(this["DefaultMaintenanceA"]));
            }
            set {
                this["DefaultMaintenanceA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultMaintenanceB {
            get {
                return ((string)(this["DefaultMaintenanceB"]));
            }
            set {
                this["DefaultMaintenanceB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultMaintenanceC {
            get {
                return ((string)(this["DefaultMaintenanceC"]));
            }
            set {
                this["DefaultMaintenanceC"] = value;
            }
        }
    }
}
